### ISSUE TITLE
MeRequestBuilder does not supports .Request() anymore from version 5.0.0

### ISSUE THREAD

**Issue by jai-dewani** [microsoftgraph/msgraph-training-dotnet#109]
https://github.com/microsoftgraph/msgraph-training-dotnet/blob/51ba4cfe7e1d23e274e2f2b0ecb58875f06ddaff/user-auth/GraphTutorial/GraphHelper.cs#L54-L63

Instead of the UserRequest, now we have to use requestConfiguration to configure the information we want from the query

**Comment by jai-dewani** [comment]
Any plan as to when this update will go live on learn.microsoft website?

**Comment by jasonjoh** [comment]
> Any plan as to when this update will go live on learn.microsoft website?

It's in process as we speak. ETA 5 minutes :D.
