### ISSUE TITLE
OData error when calling Users.GetAsync on AzureGovernment endpoints

### ISSUE THREAD

**Issue by jlara005** [microsoftgraph/msgraph-training-dotnet#178]
**Where did you get the code?**
- https://github.com/microsoftgraph/msgraph-training-dotnet/tree/main/app-auth/GraphAppOnlyTutorial
- https://learn.microsoft.com/en-us/graph/tutorials/dotnet-app-only?tabs=aad&tutorial-step=1

**Describe the bug**
First, I made the necessary changes to call the AzureGovernment endpoint in my code as seen in the screenshots. When I run the console app, I am able to get an access token without errors (pressing 1), but I am unable to retrieve all users (pressing 2). I am getting the error "Error getting users: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown." The app registration has already been setup and permissions have been granted as seen in the screenshots below. I followed the registration steps from the tutorial listed [here](https://learn.microsoft.com/en-us/graph/tutorials/dotnet-app-only?tabs=aad&tutorial-step=1).

**To Reproduce**
1. Change the following code in GraphHelper.cs:
```
public static void InitializeGraphForAppOnlyAuth(Settings settings)
{
    _settings = settings;

    // Ensure settings isn't null
    _ = settings ??
        throw new System.NullReferenceException("Settings cannot be null");

    _settings = settings;

    if (_clientSecretCredential == null)
    {
        _clientSecretCredential = new ClientSecretCredential(
            _settings.TenantId, _settings.ClientId, _settings.ClientSecret, new ClientSecretCredentialOptions() { AuthorityHost = AzureAuthorityHosts.AzureGovernment });
    }

    if (_appClient == null)
    {
        _appClient = new GraphServiceClient(_clientSecretCredential,
            // Use the default scope, which will request the scopes
            // configured on the app registration
            new[] {"https://graph.microsoft.us/.default"});
    }
}
// </AppOnlyAuthConfigSnippet>

// <GetAppOnlyTokenSnippet>
public static async Task<string> GetAppOnlyTokenAsync()
{
    // Ensure credential isn't null
    _ = _clientSecretCredential ??
        throw new System.NullReferenceException("Graph has not been initialized for app-only auth");

    // Request token with given scopes
    var context = new TokenRequestContext(new[] {"https://graph.microsoft.us/.default"});
    var response = await _clientSecretCredential.GetTokenAsync(context);
    return response.Token;
}
// </GetAppOnlyTokenSnippet>
```
3. Run the application

**Expected behavior**
I am expecting to see all listed users in my test tenant hosted in Azure Gov

**Screenshots**
Code changes:
![image](https://github.com/microsoftgraph/msgraph-training-dotnet/assets/29823126/32969b97-44ac-472d-af94-b57aaea388d0)

Error: 
![image](https://github.com/microsoftgraph/msgraph-training-dotnet/assets/29823126/24552bd0-f3ca-4320-9662-03f417b1916f)

Permissions:
![image](https://github.com/microsoftgraph/msgraph-training-dotnet/assets/29823126/321da4d5-f27e-4b34-acc6-614652ad867d)

**Dependency versions**
- Azure Identity 1.10.0
- Microsoft.Graph 5.26.0

**Comment by jasonjoh** [comment]
I believe that you need to pass an additional parameter to the constructor of `GraphServiceClient` to make it use the US Gov endpoint. You're passing the right auth scope in the second parameter, but there's a third optional parameter `baseUrl`.

Try this:

```csharp
_appClient = new GraphServiceClient(_clientSecretCredential,
    // Use the default scope, which will request the scopes
    // configured on the app registration
    new[] {"https://graph.microsoft.us/.default"},
    "https://graph.microsoft.us/v1.0");
```

If that doesn't do the trick, please set a breakpoint on the `catch` statement (see below) and inspect the exception, there should be more info inside it.

https://github.com/microsoftgraph/msgraph-training-dotnet/blob/31bfcdc3323e74ae76a36b7f579395d151bed87a/app-auth/GraphAppOnlyTutorial/Program.cs#L111

**Comment by jlara005** [comment]
Many thanks @jasonjoh ! That did the trick. I am able to see all the users.
